version: '3.9'
services:

  php:
    restart: unless-stopped
    build:
      context: ./docker/php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE:-off}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT:-5902}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST:-host.docker.internal}
        SYMFONY_CLI_VERSION: 4.23.2
    ports:
      - "${PHP_PORT:-9000}:9001"
    volumes:
      - ./:/var/www/symfony:cached
      - ./docker/logs/symfony:/var/www/symfony/var/log:cached

  nginx:
    restart: unless-stopped
    build:
      context: ./docker/nginx
      args:
        NGINX_SYMFONY_SERVER_NAME: ${NGINX_SYMFONY_SERVER_NAME:-symfony.localhost}
        KIBANA_PORT:-81: ${KIBANA_PORT:-81}
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - php
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template
      - NGINX_SYMFONY_SERVER_NAME=${NGINX_SYMFONY_SERVER_NAME:-symfony.localhost}
    volumes:
      - ./docker/logs/nginx:/var/log/nginx:cached
      - ./:/var/www/symfony:cached
volumes:
  db-data:
    external: true

networks:
  default:
    name: portfolio
